### ISSUE TITLE
Please release a demo, [I dont know how to use typescript]

### ISSUE THREAD

**Issue by 888luck8** [schlawg/lila-stockfish-web#1]
Can you put index.html or how ever to use this..... 

I understand you can do 

npm i lila-stockfish-web

.... its really annoying I want to play against stockfish16 in the web... like I can already do with stockfish14

ls node_modules/lila-stockfish-web/

fsf.js         linrock-nnue-12.js         linrock-nnue-7.wasm       sf-nnue-40.js         sf-nnue-60.wasm
fsf.wasm       linrock-nnue-12.wasm       linrock-nnue-7.worker.js  sf-nnue-40.wasm       sf-nnue-60.worker.js
fsf.worker.js  linrock-nnue-12.worker.js  package.json              sf-nnue-40.worker.js  stockfishWeb.d.ts
LICENSE        linrock-nnue-7.js          README.md                 

cd ui/ceval   
[sneed@archlinux ceval]$ npx tsx src/engines/stockfishWebEngine.ts 
          info: {
            id: '__sf16nnue40',
            name: 'Stockfish 16 NNUE · 40MB',
            short: 'SF 16 · 40MB',
            tech: 'NNUE',
            requires: ['simd', 'allowLsfw'],
            minMem: 2048,
            assets: {
              version: 'sfw003',
              root: 'npm/lila-stockfish-web',
              js: 'sf-nnue-40.js',
            },
          },
          make: (e: BrowserEngineInfo) => new StockfishWebEngine(e, this.status),

**Comment by schlawg** [comment]
This repo isn't designed for general use, it's specifically for lila. You want https://github.com/nmrugg/stockfish.js

**Comment by 888luck8** [comment]
@schlawg Its still stockfish... and I tried using stockfish.js...


I just want to use stockfish16. whats the issue with that, why this is so hard?

**Comment by schlawg** [comment]
i linked you a version of stockfish in wasm for your use case, and that's all i can do.

if you have suggestions, criticisms, or modifications to contribue, please submit them at https://github.com/lichess-org/lila-stockfish-web.

**Comment by 888luck8** [comment]
okay bro very based

**Comment by 888luck8** [comment]
oh you actually provided an answer you didnt trolled me. thank you


there is actually sf16 there! nice
